name: Deploy Flask App to GitHub Pages

on:
  push:
    branches: [ main ]

# Add concurrency control to prevent multiple simultaneous deployments
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-sqlalchemy werkzeug flask-migrate
        
    - name: Build static files
      run: |
        mkdir -p build/static
        # Copy your HTML templates to the build directory
        cp -r templates build/ || true
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
