name: Deploy Flet Web App to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-inprogress: false

env:
  PYTHON_VERSION: '3.11'
  FLET_VERSION: '0.27.5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet==${{ env.FLET_VERSION }}

    - name: Find main Python file
      run: |
        # Look for main Python files
        find . -name "*.py" -exec grep -l "ft.app(" {} \; || echo "No main.py found"
        find . -name "*.py" -exec grep -l "def main(" {} \; || echo "No main function found"

    - name: Build web app
      run: |
        # Try to find the main Python file
        MAIN_FILE=$(find . -name "*.py" -exec grep -l "ft.app\|def main" {} \; | head -1)
        if [ -z "$MAIN_FILE" ]; then
          echo "No suitable main file found. Creating a simple example..."
          cat > main.py << 'EOF'
import flet as ft

def main(page: ft.Page):
    page.title = "Flet Web App"
    page.add(
        ft.Text("Hello, Flet!", size=30, weight="bold"),
        ft.ElevatedButton("Click me!", on_click=lambda e: print("Button clicked"))
    )

ft.app(target=main)
EOF
          MAIN_FILE="main.py"
        fi
        
        echo "Using main file: $MAIN_FILE"
        flet build web --base-url ${{ github.event.repository.name }} --route-url-strategy hash -m $(basename $MAIN_FILE .py)

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
